export const LOGIN_INPUT_CHANGE = 'LOGIN_INPUT_CHANGE';
export const LOGIN_SUBMIT = 'LOGIN_SUBMIT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_RESET = 'LOGIN_RESET';
export const LOGIN_CLICK = 'LOGIN_CLICK';

export const USER_INPUT_CHANGE = 'USER_INPUT_CHANGE';
export const USER_SUBMIT = 'USER_SUBMIT';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';
export const SEARCH_RESET = 'SEARCH_RESET'
export const SEARCH_SELECT = 'SEARCH_SELECT'
export const SEARCH_DESELECT = 'SEARCH_DESELECT'
export const DISPLAY_SELECTED_RESULTS = 'DISPLAY_SELECTED_RESULTS'


export const HAS_TOKEN = 'HAS_TOKEN';