export const USER_INPUT_CHANGE = 'USER_INPUT_CHANGE';
export const USER_SUBMIT = 'USER_SUBMIT';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';
export const SEARCH_RESET = 'SEARCH_RESET'
export const SEARCH_SELECT = 'SEARCH_SELECT'
export const SEARCH_DESELECT = 'SEARCH_DESELECT'
export const DISPLAY_SELECTED_RESULTS = 'DISPLAY_SELECTED_RESULTS'